# Generated by Django 4.1.2 on 2022-10-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_alwennetworkdetailsmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alwennetworkdetailsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
