# Generated by Django 4.1.2 on 2022-10-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_alwennetworkdetailsmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alwennetworkdetailsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alwennetworkdetailsmodel',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
